# CAR price prediction

**Car Price Prediction:**
We will be predicting car price based on various features or independent variable such as:-
1)Name
2)Year
3)km_driven
4)fuel
5)seller_type
6)transmission
7)Owner

Here the output of the model will be car's selling price.
Let's start the project with importing dataset.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [2]:
# Read the dataset
dataset = pd.read_csv('car_data.csv')

In [3]:
dataset.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

# Check NULL values

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


We can see there are no null values.

In [8]:
dataset.shape

(4340, 8)

# Calculating the number of different types of owner of car.

In [6]:
dataset['owner'].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [7]:
dataset['transmission'].value_counts()

Manual       3892
Automatic     448
Name: transmission, dtype: int64

## Dividing into dependent and independent variable form by using iloc function of pandas.

In [9]:
X = dataset.iloc[:, [1,3,4,6]].values
y = dataset.iloc[:, 2].values

We just used name, fuel_type, kms_driven, transmission as our X_features to predict the selling price

## Using LabelEncoder to normalize labels and to encode the categorical variable.

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
X[:,2]=lb.fit_transform(X[:,2])
lb1 = LabelEncoder()
X[:,3]=lb1.fit_transform(X[:,3])

In [12]:
X

array([[2007, 70000, 4, 1],
       [2007, 50000, 4, 1],
       [2012, 100000, 1, 1],
       ...,
       [2009, 83000, 4, 1],
       [2016, 90000, 1, 1],
       [2016, 40000, 4, 1]], dtype=object)

See it is encoded

## Splitting dataset

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X_train[0,:])

[2015 175000 1 1]


In [14]:
X_train.shape

(3472, 4)

In [17]:
y_train

array([300000, 600000,  95000, ..., 270000, 600000, 229999], dtype=int64)

In [18]:
y_train.shape

(3472,)

In [19]:
X_test.shape

(868, 4)

In [20]:
y_test.shape

(868,)

## Creating a model of **randomforestregressor** and fitting the training data.

In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=300,random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

## Calculating accuracy of our model. 

In [22]:
accuracy = regressor.score(X_test,y_test)
print(accuracy*100,'%')

75.79783473129758 %


See we get 75% accuracy

Experiment on our model with our own data

In [27]:
new_data=[2017,7000,"Petrol","Manual"]
new_data[2]=lb.fit_transform([new_data[2]])[0]
new_data[3]=lb1.fit_transform([new_data[3]])[0]

By using model predicting the output for testing value.

In [28]:
print(new_data)
regressor.predict([new_data])

[2017, 7000, 0, 0]


array([6716550.])

See, it has given us car price something around 6 lakh.

## Creating pkl file that we are going to use in flask app.

In [29]:
import pickle
pickle.dump(regressor,open('regressor.pkl','wb'))
pickle.dump(lb,open('lb','wb'))
pickle.dump(lb1,open('lb1','wb'))